create table if not exists schema_versions (
    id bigint generated by default as identity primary key,
    version varchar(64) not null unique,
    description text not null,
    applied_at timestamptz not null default now()
);

insert into schema_versions (version, description)
values ('202607240001', 'phase 1 foundation')
on conflict (version) do nothing;

create schema if not exists app;

create or replace function app.current_workspace_id()
returns uuid
language sql
stable
as $$
    select nullif(current_setting('app.current_workspace_id', true), '')::uuid
$$;
