-- 外盘原油行情:布伦特与 WTI(2026-09-16 运营者「那把这 2 个接进来吧,
-- **不用接入套利,只接数据**」)。
--
-- 用途:算 SC / FU 对 Brent / WTI 的相关性与 beta。此前库里只有国内品种,
-- 而运营者实际交易的是内外盘联动 —— 估 beta 只能拿两个时点硬算,
-- 2026-09-15 当场估错两次(0.55 与 3.85,实际约 1.08,是运营者拿盘面数据纠正的)。
-- **这是个结构性盲区,不是临时需求。**
--
-- 为什么**不塞进 price_history**,三条独立理由:
--
-- 1. 它三个 CHECK 全挡:`price_history_exchange_allowed` 只认
--    DCE/CZCE/SHFE/CFFEX/INE、`instrument_shape` 要 `^[A-Z]{1,2}$`、
--    `contract_shape` 要 `^[A-Z]{1,2}[0-9]{4}$`。三个都得放宽,影响面盖住全部国内行情;
-- 2. 外盘取的是**主力连续**,不是真实合约。`DATABASE_DESIGN.md` 对
--    `continuous_series_observations` 写明「**不得冒充实际合约行情**」——
--    把合成序列塞进合约表,就是在冒充;
-- 3. **美元计价**。与人民币品种同表,点值、基差、盈亏折算迟早有人算错。
--
-- 边界写死:**不进 `monitor_scope`**(不做套利监控)、不进引擎、不进席位。
-- 只是一张给分析用的行情表。
--
-- `symbol` 沿用上游代码不自造:**OIL = 布伦特、CL = WTI**
-- (akshare `futures_foreign_hist` 的 symbol,该接口走新浪源;
-- 东财那条 `futures_global_hist_em` 在 qh 上实测 RemoteDisconnected,不可用)。
--
-- **上游两个空洞,落库必须是 NULL 不是 0**(DEC-073 的教训:0 不是价格,是缺失):
--   · OIL 的 `position` 恒 0 —— 没有持仓量;
--   · CL 的 `volume` 与 `settlement` 恒 0 —— 没有成交量、没有结算价。
-- 由 fetch-overseas.py 在出 CSV 时转空,这里的 CHECK 只保证「非负」,
-- 不保证「有值」。

begin;

create table if not exists overseas_price_daily (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null references workspaces (id) on delete restrict,
    symbol text not null,
    trade_date date not null,
    open_price numeric(20, 8),
    high_price numeric(20, 8),
    low_price numeric(20, 8),
    close_price numeric(20, 8),
    settlement_price numeric(20, 8),
    volume numeric(24, 8),
    open_interest numeric(24, 8),
    source text not null,
    loaded_at timestamptz not null default now(),
    updated_at timestamptz
);

alter table overseas_price_daily
    drop constraint if exists overseas_price_daily_identity,
    add constraint overseas_price_daily_identity
        unique (workspace_id, symbol, trade_date, source);

alter table overseas_price_daily
    drop constraint if exists overseas_price_daily_symbol_allowed,
    -- 白名单而不是任意字符串:拼错一个代码就是一条永远对不上的序列,
    -- 而且不会报错。要加品种往这里加。
    add constraint overseas_price_daily_symbol_allowed
        check (symbol = any (array['OIL'::text, 'CL'::text]));

alter table overseas_price_daily
    drop constraint if exists overseas_price_daily_has_a_price,
    -- 收盘价是这张表存在的理由;没有它这行没有意义。
    add constraint overseas_price_daily_has_a_price
        check (close_price is not null and close_price > 0);

alter table overseas_price_daily
    drop constraint if exists overseas_price_daily_range_ordered,
    add constraint overseas_price_daily_range_ordered
        check (high_price is null or low_price is null or high_price >= low_price);

alter table overseas_price_daily
    drop constraint if exists overseas_price_daily_not_negative,
    add constraint overseas_price_daily_not_negative
        check (coalesce(volume, 0) >= 0 and coalesce(open_interest, 0) >= 0);

create index if not exists overseas_price_daily_lookup
    on overseas_price_daily (workspace_id, symbol, trade_date desc);

-- 与 price_history / spread_monitor_daily 同一套:enable + force。
-- 采集链用的 futures_app 是 superuser + bypassrls,写入不受影响;
-- 强制 RLS 挡的是将来通过 runtime 角色读这张表的路径。
alter table overseas_price_daily enable row level security;
alter table overseas_price_daily force row level security;

drop policy if exists overseas_price_daily_workspace_isolation on overseas_price_daily;
create policy overseas_price_daily_workspace_isolation on overseas_price_daily
    using (workspace_id = app.current_workspace_id())
    with check (workspace_id = app.current_workspace_id());

grant select on overseas_price_daily to futures_runtime;

insert into schema_versions (version, description)
values ('202609160001',
        'Overseas crude continuous quotes (Brent OIL / WTI CL) for correlation analysis only')
on conflict (version) do nothing;

commit;
