FROM rust:1.96.0-bookworm AS builder
WORKDIR /app
COPY rust ./rust
WORKDIR /app/rust
RUN cargo build --release -p api

FROM debian:13.2-slim
WORKDIR /app
COPY --from=builder /app/rust/target/release/api /app/api
EXPOSE 8080
CMD ["/app/api"]
