FROM rust:1.96.0-bookworm AS builder
WORKDIR /app
COPY rust ./rust
WORKDIR /app/rust
RUN cargo build --release -p worker

FROM debian:13.2-slim
WORKDIR /app
COPY --from=builder /app/rust/target/release/worker /app/worker
CMD ["/app/worker"]
