[package]
name = "application"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
calamine.workspace = true
domain.workspace = true
encoding_rs.workspace = true
serde.workspace = true
time.workspace = true
utoipa.workspace = true
uuid.workspace = true
